name: ScapeArt
url: http://scapeart.github.io
markdown: kramdown
permalink: /:year/:month/:title.html
exclude: [README.md]
paginate: 3
paginate_path: "index/page:num.html"
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-github-metadata
feed:
  path: atom.xml
